# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 14:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_postadd'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Register',
        ),
    ]
