# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-11 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180911_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadd',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Register'),
        ),
    ]
