# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-13 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180911_2043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postedit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Postadd')),
            ],
        ),
    ]
