# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 11:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_postedit'),
    ]

    operations = [
        migrations.AddField(
            model_name='postadd',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.date(2018, 9, 29)),
        ),
    ]
