# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 11:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postadd_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadd',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 29, 12, 53, 6, 789959)),
        ),
    ]
