# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-29 14:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20180929_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='postadd',
            name='img',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='postadd',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 29, 15, 45, 41, 104447)),
        ),
    ]
