# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-30 08:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20180929_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadd',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 30, 9, 44, 38, 880350)),
        ),
    ]
