# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 09:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20180930_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadd',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 1, 10, 28, 44, 907052)),
        ),
    ]
