# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 11:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20181001_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadd',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 1, 12, 52, 27, 777633)),
        ),
    ]
